# Generated by Django 4.2.11 on 2026-03-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hubapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExchangeRequest',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
